default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: base_rest_eshop_api_development

test:
  <<: *default
  database: base_rest_eshop_api_test

production:
  <<: *default
  database: base_rest_eshop_api_production
  username: base_rest_eshop_api
  password: <%= ENV['BASE_REST_ESHOP_API_DATABASE_PASSWORD'] %>
